-- Migration: Judge Device Sessions System
-- Purpose: Implement device-based judge identity selection without user accounts
-- Requirements: Device locking, judge identity management, no authentication required

-- Drop the old judge_sessions table and recreate with device-based logic
DROP TABLE IF EXISTS judge_sessions CASCADE;

-- Create new judge_sessions table for device-based sessions
CREATE TABLE judge_sessions (
    id SERIAL PRIMARY KEY,
    judge_id INTEGER NOT NULL REFERENCES judges(id) ON DELETE CASCADE,
    device_id VARCHAR(255) NOT NULL, -- UUID generated by frontend
    judge_name VARCHAR(255) NOT NULL,
    judge_code VARCHAR(50) NOT NULL,
    ip_address INET,
    user_agent TEXT,
    browser_fingerprint TEXT, -- Additional device identification
    started_at TIMESTAMP DEFAULT NOW(),
    last_activity TIMESTAMP DEFAULT NOW(),
    expires_at TIMESTAMP DEFAULT (NOW() + INTERVAL '8 hours'),
    ended_at TIMESTAMP NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    
    -- Ensure one active session per judge (device locking)
    CONSTRAINT unique_active_judge UNIQUE (judge_id, is_active) DEFERRABLE INITIALLY DEFERRED
);

-- Create indexes for performance
CREATE INDEX idx_judge_sessions_judge_id ON judge_sessions(judge_id);
CREATE INDEX idx_judge_sessions_device_id ON judge_sessions(device_id);
CREATE INDEX idx_judge_sessions_active ON judge_sessions(is_active, expires_at);
CREATE INDEX idx_judge_sessions_last_activity ON judge_sessions(last_activity);

-- Update scores table to reference new judge_sessions
ALTER TABLE scores DROP COLUMN IF EXISTS judge_session_id;
ALTER TABLE scores DROP COLUMN IF EXISTS judge_name;
ALTER TABLE scores ADD COLUMN judge_session_id INTEGER REFERENCES judge_sessions(id);
ALTER TABLE scores ADD COLUMN judge_name VARCHAR(255);

-- Create index for scores judge session tracking
CREATE INDEX idx_scores_judge_session ON scores(judge_session_id);

-- Add trigger to update updated_at and last_activity timestamps
CREATE OR REPLACE FUNCTION update_judge_sessions_timestamps()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    -- Update last_activity on any update
    IF TG_OP = 'UPDATE' THEN
        NEW.last_activity = NOW();
    END IF;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_judge_sessions_timestamps
    BEFORE UPDATE ON judge_sessions
    FOR EACH ROW
    EXECUTE FUNCTION update_judge_sessions_timestamps();

-- Function to automatically end expired sessions
CREATE OR REPLACE FUNCTION cleanup_expired_judge_sessions()
RETURNS INTEGER AS $$
DECLARE
    expired_count INTEGER;
BEGIN
    UPDATE judge_sessions 
    SET is_active = false, 
        ended_at = NOW(),
        updated_at = NOW()
    WHERE is_active = true 
      AND expires_at < NOW();
    
    GET DIAGNOSTICS expired_count = ROW_COUNT;
    RETURN expired_count;
END;
$$ language 'plpgsql';

-- Function to check if a judge is available for selection
CREATE OR REPLACE FUNCTION is_judge_available(judge_id_param INTEGER)
RETURNS BOOLEAN AS $$
DECLARE
    judge_active BOOLEAN;
    has_active_session BOOLEAN;
BEGIN
    -- Check if judge is active
    SELECT is_active INTO judge_active 
    FROM judges 
    WHERE id = judge_id_param;
    
    IF NOT FOUND OR NOT judge_active THEN
        RETURN false;
    END IF;
    
    -- Check if judge has an active session
    SELECT EXISTS(
        SELECT 1 FROM judge_sessions 
        WHERE judge_id = judge_id_param 
          AND is_active = true 
          AND expires_at > NOW()
    ) INTO has_active_session;
    
    RETURN NOT has_active_session;
END;
$$ language 'plpgsql';

-- Function to get available judges for selection
CREATE OR REPLACE FUNCTION get_available_judges()
RETURNS TABLE(
    id INTEGER,
    name VARCHAR(255),
    display_name VARCHAR(255),
    code VARCHAR(50),
    is_available BOOLEAN,
    current_device_id VARCHAR(255)
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        j.id,
        j.name,
        j.display_name,
        j.code,
        (j.is_active AND NOT EXISTS(
            SELECT 1 FROM judge_sessions js 
            WHERE js.judge_id = j.id 
              AND js.is_active = true 
              AND js.expires_at > NOW()
        )) as is_available,
        js.device_id as current_device_id
    FROM judges j
    LEFT JOIN judge_sessions js ON j.id = js.judge_id 
        AND js.is_active = true 
        AND js.expires_at > NOW()
    WHERE j.is_active = true
    ORDER BY j.name;
END;
$$ language 'plpgsql';

-- Ensure judges table has the right structure
ALTER TABLE judges ALTER COLUMN is_active SET DEFAULT true;

-- Insert sample judges if they don't exist (for testing)
INSERT INTO judges (name, display_name, code, is_active) VALUES
('张三', '张三评委', 'J001', true),
('李四', '李四评委', 'J002', true),
('王五', '王五评委', 'J003', true),
('赵六', '赵六评委', 'J004', true),
('钱七', '钱七评委', 'J005', true),
('孙八', '孙八评委', 'J006', true),
('周九', '周九评委', 'J007', true),
('吴十', '吴十评委', 'J008', true)
ON CONFLICT (code) DO NOTHING;

-- Comments for documentation
COMMENT ON TABLE judge_sessions IS 'Device-based judge sessions for identity selection without user accounts';
COMMENT ON COLUMN judge_sessions.device_id IS 'Unique device identifier (UUID) generated by frontend';
COMMENT ON COLUMN judge_sessions.browser_fingerprint IS 'Additional browser fingerprinting for device identification';
COMMENT ON COLUMN judge_sessions.last_activity IS 'Last activity timestamp for session management';
COMMENT ON CONSTRAINT unique_active_judge ON judge_sessions IS 'Ensures only one active session per judge (device locking)';
COMMENT ON FUNCTION is_judge_available(INTEGER) IS 'Checks if a judge is available for selection (active and not in use)';
COMMENT ON FUNCTION get_available_judges() IS 'Returns all judges with their availability status';
COMMENT ON FUNCTION cleanup_expired_judge_sessions() IS 'Automatically ends expired judge sessions';