-- ============================================================================
-- Supabase Migration: Judge Device Sessions System (Complete)
-- ============================================================================
-- Purpose: Implement device-based judge identity selection without user accounts
-- Requirements: Device locking, judge identity management, session tracking
-- Date: 2024
-- 
-- This script combines multiple migrations:
-- - 006_judge_device_sessions.sql
-- - 007_fix_unique_constraint.sql
-- - 008_add_updated_at_to_scores.sql
-- - 009_fix_scores_judge_fk.sql
--
-- IMPORTANT: Run this script in Supabase SQL Editor
-- ============================================================================

-- ============================================================================
-- PART 1: Drop existing judge_sessions table and recreate
-- ============================================================================

-- Drop the old judge_sessions table if exists
DROP TABLE IF EXISTS judge_sessions CASCADE;

-- Create new judge_sessions table for device-based sessions
CREATE TABLE judge_sessions (
    id SERIAL PRIMARY KEY,
    judge_id INTEGER NOT NULL REFERENCES judges(id) ON DELETE CASCADE,
    device_id VARCHAR(255) NOT NULL, -- UUID generated by frontend
    judge_name VARCHAR(255) NOT NULL,
    judge_code VARCHAR(50) NOT NULL,
    ip_address INET,
    user_agent TEXT,
    browser_fingerprint TEXT, -- Additional device identification
    started_at TIMESTAMP DEFAULT NOW(),
    last_activity TIMESTAMP DEFAULT NOW(),
    expires_at TIMESTAMP DEFAULT (NOW() + INTERVAL '8 hours'),
    ended_at TIMESTAMP NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- ============================================================================
-- PART 2: Create indexes for performance
-- ============================================================================

CREATE INDEX idx_judge_sessions_judge_id ON judge_sessions(judge_id);
CREATE INDEX idx_judge_sessions_device_id ON judge_sessions(device_id);
CREATE INDEX idx_judge_sessions_active ON judge_sessions(is_active, expires_at);
CREATE INDEX idx_judge_sessions_last_activity ON judge_sessions(last_activity);

-- Create partial unique index for device locking (only one active session per judge)
-- This replaces the problematic UNIQUE constraint with boolean values
CREATE UNIQUE INDEX idx_unique_active_judge 
ON judge_sessions (judge_id) 
WHERE is_active = true;

-- ============================================================================
-- PART 3: Update scores table to reference judge_sessions
-- ============================================================================

-- Add judge_session_id column if not exists
ALTER TABLE scores ADD COLUMN IF NOT EXISTS judge_session_id INTEGER REFERENCES judge_sessions(id);

-- Add judge_name column if not exists (for denormalization)
ALTER TABLE scores ADD COLUMN IF NOT EXISTS judge_name VARCHAR(255);

-- Add updated_at column for partial score updates
ALTER TABLE scores ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Update existing records to have updated_at = submitted_at
UPDATE scores SET updated_at = submitted_at WHERE updated_at IS NULL;

-- Create indexes for scores table
CREATE INDEX IF NOT EXISTS idx_scores_judge_session ON scores(judge_session_id);
CREATE INDEX IF NOT EXISTS idx_scores_updated ON scores(updated_at DESC);

-- ============================================================================
-- PART 4: Fix scores.judge_id foreign key constraint
-- ============================================================================

-- Drop the existing foreign key constraint (if exists)
ALTER TABLE scores DROP CONSTRAINT IF EXISTS scores_judge_id_fkey;

-- Add new foreign key constraint referencing judges table (not users table)
-- This allows device-based judge sessions to submit scores
ALTER TABLE scores 
ADD CONSTRAINT scores_judge_id_fkey 
FOREIGN KEY (judge_id) 
REFERENCES judges(id) 
ON DELETE CASCADE;

-- ============================================================================
-- PART 5: Create triggers and functions
-- ============================================================================

-- Trigger function to update timestamps on judge_sessions
CREATE OR REPLACE FUNCTION update_judge_sessions_timestamps()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    -- Update last_activity on any update
    IF TG_OP = 'UPDATE' THEN
        NEW.last_activity = NOW();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger
DROP TRIGGER IF EXISTS update_judge_sessions_timestamps ON judge_sessions;
CREATE TRIGGER update_judge_sessions_timestamps
    BEFORE UPDATE ON judge_sessions
    FOR EACH ROW
    EXECUTE FUNCTION update_judge_sessions_timestamps();

-- ============================================================================
-- PART 6: Create utility functions
-- ============================================================================

-- Function to automatically end expired sessions
CREATE OR REPLACE FUNCTION cleanup_expired_judge_sessions()
RETURNS INTEGER AS $$
DECLARE
    expired_count INTEGER;
BEGIN
    UPDATE judge_sessions 
    SET is_active = false, 
        ended_at = NOW(),
        updated_at = NOW()
    WHERE is_active = true 
      AND expires_at < NOW();
    
    GET DIAGNOSTICS expired_count = ROW_COUNT;
    RETURN expired_count;
END;
$$ LANGUAGE plpgsql;

-- Function to check if a judge is available for selection
CREATE OR REPLACE FUNCTION is_judge_available(judge_id_param INTEGER)
RETURNS BOOLEAN AS $$
BEGIN
    -- Check if judge exists and is active, and has no active session
    RETURN (
        SELECT 
            CASE 
                WHEN j.is_active = false THEN false
                WHEN EXISTS(
                    SELECT 1 FROM judge_sessions js
                    WHERE js.judge_id = judge_id_param
                      AND js.is_active = true
                      AND js.expires_at > NOW()
                ) THEN false
                ELSE true
            END
        FROM judges j
        WHERE j.id = judge_id_param
    );
END;
$$ LANGUAGE plpgsql;

-- Function to get available judges for selection
CREATE OR REPLACE FUNCTION get_available_judges()
RETURNS TABLE(
    id INTEGER,
    name VARCHAR(255),
    display_name VARCHAR(255),
    code VARCHAR(50),
    is_available BOOLEAN,
    current_device_id VARCHAR(255)
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        j.id,
        j.name,
        j.display_name,
        j.code,
        (j.is_active AND NOT EXISTS(
            SELECT 1 FROM judge_sessions js 
            WHERE js.judge_id = j.id 
              AND js.is_active = true 
              AND js.expires_at > NOW()
        )) as is_available,
        js.device_id as current_device_id
    FROM judges j
    LEFT JOIN judge_sessions js ON j.id = js.judge_id 
        AND js.is_active = true 
        AND js.expires_at > NOW()
    WHERE j.is_active = true
    ORDER BY j.name;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- PART 7: Ensure judges table has correct structure
-- ============================================================================

-- Ensure is_active column has default value
ALTER TABLE judges ALTER COLUMN is_active SET DEFAULT true;

-- ============================================================================
-- PART 8: Insert sample judges (optional - for testing)
-- ============================================================================

-- Insert sample judges if they don't exist
-- Remove this section if you don't want sample data
INSERT INTO judges (name, display_name, code, is_active) VALUES
('张三', '张三评委', 'J001', true),
('李四', '李四评委', 'J002', true),
('王五', '王五评委', 'J003', true),
('赵六', '赵六评委', 'J004', true),
('钱七', '钱七评委', 'J005', true),
('孙八', '孙八评委', 'J006', true),
('周九', '周九评委', 'J007', true),
('吴十', '吴十评委', 'J008', true),
('郑十一', '郑十一评委', 'J009', true),
('王十二', '王十二评委', 'J010', true)
ON CONFLICT (code) DO NOTHING;

-- ============================================================================
-- PART 9: Add comments for documentation
-- ============================================================================

COMMENT ON TABLE judge_sessions IS 'Device-based judge sessions for identity selection without user accounts';
COMMENT ON COLUMN judge_sessions.device_id IS 'Unique device identifier (UUID) generated by frontend';
COMMENT ON COLUMN judge_sessions.browser_fingerprint IS 'Additional browser fingerprinting for device identification';
COMMENT ON COLUMN judge_sessions.last_activity IS 'Last activity timestamp for session management';
COMMENT ON COLUMN judge_sessions.expires_at IS 'Session expiration time (default 8 hours from start)';
COMMENT ON COLUMN judge_sessions.is_active IS 'Whether the session is currently active';

COMMENT ON INDEX idx_unique_active_judge IS 'Ensures only one active session per judge (device locking)';

COMMENT ON COLUMN scores.judge_session_id IS 'Reference to the judge session that submitted this score';
COMMENT ON COLUMN scores.judge_name IS 'Denormalized judge name for quick access';
COMMENT ON COLUMN scores.updated_at IS 'Timestamp when the score was last updated (for partial updates)';

COMMENT ON FUNCTION is_judge_available(INTEGER) IS 'Checks if a judge is available for selection (active and not in use)';
COMMENT ON FUNCTION get_available_judges() IS 'Returns all judges with their availability status';
COMMENT ON FUNCTION cleanup_expired_judge_sessions() IS 'Automatically ends expired judge sessions';

-- ============================================================================
-- PART 10: Verification queries (optional - comment out if not needed)
-- ============================================================================

-- Verify judge_sessions table structure
DO $$
BEGIN
    RAISE NOTICE 'Judge sessions table created successfully';
    RAISE NOTICE 'Checking table structure...';
END $$;

-- Show table structure
SELECT 
    column_name, 
    data_type, 
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_name = 'judge_sessions'
ORDER BY ordinal_position;

-- Show indexes
SELECT 
    indexname,
    indexdef
FROM pg_indexes
WHERE tablename = 'judge_sessions';

-- Show functions
SELECT 
    routine_name,
    routine_type
FROM information_schema.routines
WHERE routine_name LIKE '%judge%'
ORDER BY routine_name;

-- ============================================================================
-- Migration Complete
-- ============================================================================

DO $$
BEGIN
    RAISE NOTICE '============================================================================';
    RAISE NOTICE 'Judge Device Sessions Migration Complete!';
    RAISE NOTICE '============================================================================';
    RAISE NOTICE 'Created:';
    RAISE NOTICE '  - judge_sessions table with device-based session tracking';
    RAISE NOTICE '  - Indexes for performance optimization';
    RAISE NOTICE '  - Unique constraint for device locking (one active session per judge)';
    RAISE NOTICE '  - Triggers for automatic timestamp updates';
    RAISE NOTICE '  - Utility functions for session management';
    RAISE NOTICE '  - Updated scores table with session tracking';
    RAISE NOTICE '  - Fixed foreign key constraints';
    RAISE NOTICE '';
    RAISE NOTICE 'Next steps:';
    RAISE NOTICE '  1. Verify the migration by checking the tables and functions';
    RAISE NOTICE '  2. Test judge identity selection from the frontend';
    RAISE NOTICE '  3. Monitor session creation and expiration';
    RAISE NOTICE '  4. Remove sample judges if not needed (J001-J010)';
    RAISE NOTICE '============================================================================';
END $$;
