// Judge and Judge Session interfaces
// Requirements: Device-based judge identity selection system without user accounts

export interface Judge {
  id: number;
  name: string;
  display_name: string;
  code: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  // Session tracking fields (from admin judge list)
  is_currently_active?: boolean; // Whether judge has an active session right now
  last_session_start?: string | null; // Most recent session start time
  current_device_id?: string | null; // Device ID of current active session
  current_session_started_at?: string | null; // When current session started
  current_session_last_activity?: string | null; // Last activity of current session
  current_session_expires_at?: string | null; // When current session expires
}

// New device-based judge session (no user_id required)
export interface JudgeSession {
  id: number;
  judge_id: number;
  device_id: string; // UUID generated by frontend
  judge_name: string;
  judge_code: string;
  ip_address?: string;
  user_agent?: string;
  browser_fingerprint?: string;
  started_at: string;
  last_activity: string;
  expires_at: string;
  ended_at?: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

// Available judge for selection (includes availability status)
export interface AvailableJudge {
  id: number;
  name: string;
  display_name: string;
  code: string;
  is_available: boolean;
  current_device_id?: string;
}

// Judge selection request (device-based)
export interface JudgeSelectionRequest {
  judgeId: number;
  deviceId: string;
  browserFingerprint?: string;
}

// Judge selection response (no JWT needed)
export interface JudgeSelectionResponse {
  success: boolean;
  message: string;
  data: {
    session: {
      id: number;
      judgeId: number;
      judgeName: string;
      judgeCode: string;
      deviceId: string;
      startedAt: string;
      expiresAt: string;
    };
  };
}

// Current session response (device-based)
export interface CurrentSessionResponse {
  success: boolean;
  data: {
    sessionId: number;
    judgeId: number;
    judgeName: string;
    judgeCode: string;
    deviceId: string;
    startedAt: string;
    lastActivity: string;
    expiresAt: string;
    isActive: boolean;
  } | null;
  message?: string;
}

// Available judges response
export interface AvailableJudgesResponse {
  success: boolean;
  data: {
    judges: AvailableJudge[];
    total: number;
  };
}

export interface JudgeStats {
  judges: {
    total: number;
    active: number;
    inactive: number;
    in_use: number; // Currently selected by devices
  };
  sessions: {
    total: number;
    active: number;
    ended: number;
    expired: number;
  };
}

export interface JudgeListResponse {
  success: boolean;
  count: number;
  data: {
    judges: Judge[];
    total: number;
  };
}

export interface JudgeDetailResponse {
  success: boolean;
  data: {
    judge: Judge;
  };
}

export interface JudgeStatsResponse {
  success: boolean;
  data: JudgeStats;
}

export interface CreateJudgeRequest {
  name: string;
  display_name: string;
  code: string;
}

export interface UpdateJudgeRequest {
  name?: string;
  display_name?: string;
  code?: string;
  is_active?: boolean;
}

// Device session management
export interface EndSessionRequest {
  sessionId: number;
  deviceId: string;
}

export interface ExtendSessionRequest {
  sessionId: number;
  deviceId: string;
}

// Type aliases for consistency
export type JudgeCreateRequest = CreateJudgeRequest;
export type JudgeUpdateRequest = UpdateJudgeRequest;